update Snapshots.md
sandboxie-plus/sandboxie-docs pull request #112
Opened 2023-06-01 11:54 UTC by wilders-soccerfan

update Snapshots.md and add image files to 'media' folder

2023-06-02 18:55 UTC, offhub commented
Looks good. 👍

2023-06-02 18:56 UTC, offhub approved these changes

2023-06-02 20:33 UTC, isaak654 requested changes

2023-06-02 20:33 UTC, isaak654 commented on PlusContent/BoxSnapshots.md
> +- Create a pre-update snapshot (for a baseline you can revert to, if need be-).
```suggestion
- Create a pre-update snapshot (for a baseline you can revert to, if need be). 
```

I'm not sure about this hyphen.

2023-06-02 20:39 UTC, isaak654 requested changes

2023-06-02 20:39 UTC, isaak654 commented on PlusContent/BoxSnapshots.md
> +is saved in the file **snapshot.ini** in the box folder.
```suggestion
- The snapshot layout and information on the current (default) snapshot are saved in the file **snapshot.ini** in the box folder.
```

2023-06-02 20:41 UTC, isaak654 requested changes

2023-06-02 20:41 UTC, isaak654 commented on PlusContent/BoxSnapshots.md
> +click 'Snapshots Manager' from the drop-down list. See image below.
```suggestion
To get started, open the Sandman GUI, right-click on the desired sandbox and click 'Snapshots Manager' from the drop-down list. See image below.
```

2023-06-02 20:45 UTC, wilders-soccerfan commented on PlusContent/BoxSnapshots.md
> +click 'Snapshots Manager' from the drop-down list. See image below.
Agreed!

2023-06-02 20:46 UTC, wilders-soccerfan commented on PlusContent/BoxSnapshots.md
> +- Create a pre-update snapshot (for a baseline you can revert to, if need be-).
Should not be there!

2023-06-02 20:48 UTC, wilders-soccerfan commented on PlusContent/BoxSnapshots.md
> +is saved in the file **snapshot.ini** in the box folder.
Looks good. My grammar is weak.

2023-06-04 15:30 UTC, isaak654 requested changes

2023-06-04 15:30 UTC, isaak654 commented on PlusContent/BoxSnapshots.md
> +To get started, open the Sandman GUI, right-click on the desired sandbox and click 'Snapshots Manager' from the drop-down list. See image below.
```suggestion
A **snapshot** saves the current state of a sandbox. You can create multiple snapshots of a box at different times and make one of the snapshots the default. To get started, open the Sandman GUI, right-click on the desired sandbox and click 'Snapshots Manager' from the drop-down list. See image below.
```

2023-06-04 17:07 UTC, isaak654 approved these changes

2023-06-05 22:48 UTC, isaak654 requested changes
[Box_Snapshot2.png](https://raw.githubusercontent.com/sandboxie-plus/sandboxie-docs/db088731d1fe5ba0ca5d429c720497b212afc716/Media/Box_Snapshot2.png) is lower quality than the others two, could you produce a better one? 
I find the text not particularly crisp.

2023-06-06 02:10 UTC, wilders-soccerfan commented
Hope the attached Box_Snapshot.png is satisfactory (the old one was from
David's post on Wilders).
Thank you for your painstaking attention to detail. Much appreciated. It
seems to have become a lost art in our hurried world.

On Mon, Jun 5, 2023 at 6:49 PM isaak654 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Box_Snapshot2.png
> <https://raw.githubusercontent.com/sandboxie-plus/sandboxie-docs/db088731d1fe5ba0ca5d429c720497b212afc716/Media/Box_Snapshot2.png>
> is lower quality than the others two, could you produce a better one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sandboxie-plus/sandboxie-docs/pull/112#pullrequestreview-1463679856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ5HYA7RM4C2TAKL2RL7GBTXJZO6JANCNFSM6AAAAAAYWZXVTU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-06 09:16 UTC, isaak654 commented
> Hope the attached Box_Snapshot.png is satisfactory

Unfortunately GitHub doesn't seem to attach images via email, it happened to other users as well.

2023-06-06 10:58 UTC, wilders-soccerfan reviewed
![Box_Snapshot2](https://github.com/sandboxie-plus/sandboxie-docs/assets/108690435/73bb8119-79ef-4e45-86f6-62e02011579f)

Hope this works.

2023-06-06 11:36 UTC, isaak654 commented
Please attach a new one with only the Snapshots dialog, to be taken specifically from the LockBox sandbox.

2023-06-06 12:08 UTC, wilders-soccerfan reviewed
![Box_Snapshot2](https://github.com/sandboxie-plus/sandboxie-docs/assets/108690435/af846a96-33d9-464f-af9c-cad901b586ee)
Here it is.

2023-06-06 12:20 UTC, isaak654 approved these changes

2023-06-06 12:27 UTC, merged