Add discord
sandboxie-plus/sandboxie-docs pull request #157
Opened 2024-02-03 20:46 UTC by kokofixcomputers

Add discord server

2024-02-03 21:02 UTC, isaak654 requested changes

2024-02-03 21:02 UTC, isaak654 commented on README.md
> +[![Join our Discord Server](https://img.shields.io/badge/Join-Our%20Discord%20Server%20for%20bugs%20,%20feedback%20and%20more!-blue?style=for-the-badge&logo=discord)](https://discord.gg/TZDC3qbCSk)
```suggestion

[![Join our Discord Server](https://img.shields.io/badge/Join-Our%20Discord%20Server%20for%20bugs%20,%20feedback%20and%20more!-blue?style=for-the-badge&logo=discord)](https://discord.gg/TZDC3qbCSk)
```

2024-02-03 21:06 UTC, isaak654 approved these changes

2024-02-03 21:07 UTC, kokofixcomputers commented
Thanks @isaak654

2024-02-05 22:19 UTC, isaak654 requested changes

2024-02-05 22:19 UTC, isaak654 commented on README.md
> +[![Join our Discord Server](https://img.shields.io/badge/Join-Our%20Discord%20Server%20for%20bugs%20,%20feedback%20and%20more!-blue?style=for-the-badge&logo=discord)](https://discord.gg/TZDC3qbCSk)
```suggestion
[![Join our Discord Server](https://img.shields.io/badge/Join-Our%20Discord%20Server%20for%20bugs%20,%20feedback%20and%20more!-blue?style=for-the-badge&logo=discord)](https://discord.gg/S4tFu6Enne)
```

Same Discord link as https://github.com/sandboxie-plus/Sandboxie/commit/41e1ce99febaff2d4a722bcbf79346e85d232214

2024-02-16 18:00 UTC, isaak654 requested changes

2024-02-16 18:00 UTC, isaak654 commented on README.md
```suggestion

[![Markdown links Status](https://github.com/sandboxie-plus/sandboxie-docs/actions/workflows/action.yml/badge.svg)](https://github.com/sandboxie-plus/sandboxie-docs/actions/workflows/action.yml) [![Codespell Status](https://github.com/sandboxie-plus/sandboxie-docs/actions/workflows/codespell.yml/badge.svg)](https://github.com/sandboxie-plus/sandboxie-docs/actions/workflows/codespell.yml)

[![Join our Discord Server](https://img.shields.io/badge/Join-Our%20Discord%20Server%20for%20bugs%20,%20feedback%20and%20more!-blue?style=for-the-badge&logo=discord)](https://discord.gg/S4tFu6Enne)

```

2024-02-16 18:05 UTC, isaak654 approved these changes

2024-02-16 18:18 UTC, merged