Adopt MkDocs and use Read the Docs theme
sandboxie-plus/sandboxie-docs pull request #167
Opened 2024-04-08 14:14 UTC by QZLin

2024-04-08 14:39 UTC, isaak654 commented
Unless you click the plus buttons, it is not possible to directly access "Sandboxie Control" and "SBIE Messages" with Firefox 124.0.2 and MS Edge 123.0.2420.81:

https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/b56d7b46-969a-40f5-af89-2f6eb5810a04

2024-04-08 15:45 UTC, QZLin commented
That seems the expected behaviour of the mkdocs default readthedoc theme. I will try to change it.

2024-04-08 21:34 UTC, isaak654 commented
1. If you go into the "Usage Tips" page, the minus button is still displayed even when there is nothing below to collapse
2. The Sandboxie logo feels empty without a `sandboxie-docs` text next to it.
3. Search highlighting doesn't seem to be supported in the theme, so this can be skipped and postponed later

2024-04-08 21:35 UTC, isaak654 commented
1. If you go into the "Usage Tips" page, the minus button is still displayed even when there is nothing below to collapse
2. The Sandboxie logo feels empty without a `sandboxie-docs` text next to it
3. Search highlighting doesn't seem to be supported in the theme, so this can be skipped and postponed later

2024-04-10 21:18 UTC, isaak654 requested changes

2024-04-10 21:18 UTC, isaak654 commented on docs/_layouts/default.html
One of the old paths that needs cleaning up.

2024-04-10 21:18 UTC, isaak654 commented on docs/assets/css/style.scss
One of the old paths that needs cleaning up.

2024-04-10 21:18 UTC, isaak654 commented on docs/PlusContent/WFPSupport.md
Nothing against moving Content and Media to docs, but I have the impression that all other pending pull requests will end up with broken references, unless this pull request is merged for last. Can you confirm this?

2024-04-10 21:18 UTC, isaak654 commented on custom_theme/css/theme_extra.css
> +    color: #f8f8f8;
Please add:

```
label {
    font-size:100%;
}
```

```
.wy-side-nav-search .wy-dropdown>a,
.wy-side-nav-search>a {
    font-weight:normal;
}
```

2024-04-10 21:18 UTC, isaak654 commented on .github/workflows/publish.yml
> +# - requirements.txt
Can they be removed or do they have a later purpose?

2024-04-10 22:12 UTC, isaak654 commented on mkdocs.yml
> +nav:
Is the entire .md file structure automatically updated when a new file is found under the docs folder?

2024-04-11 05:46 UTC, QZLin commented on mkdocs.yml
> +nav:
Yes, page is automatically generated for new `.md` file in docs. Nav requires manual update.
The `watch` parameter only affects the live reload of the development, and the `mkdocs.yml` file, folder `docs` will always be watched.

2024-04-11 06:47 UTC, QZLin commented on docs/PlusContent/WFPSupport.md
Args of lychee-action is modified for changed doc structure
https://github.com/QZLin/sandboxie-docs/actions/runs/8642656793

2024-05-10 07:26 UTC, QZLin reviewed
Is the label of logo no longer required?

2024-06-21 19:44 UTC, isaak654 commented
I think it would be better if the text was part of the logo itself.

In this regard, I wonder if it is possible to reproduce a yellow font similar to this one: 
[105014988-575cb680-5a41-11eb-90d5-d942d28184b2.png](https://user-images.githubusercontent.com/3890945/105014988-575cb680-5a41-11eb-90d5-d942d28184b2.png)

2024-06-23 12:16 UTC, QZLin commented
a merged logo
![sandmerge](https://github.com/sandboxie-plus/sandboxie-docs/assets/38138000/87df6d8d-4a1c-4ddd-b248-5c20e42b84d7)

2024-06-23 17:00 UTC, isaak654 commented
I'm thinking of something more recognizable like this:

![342063615-87df6d8d-4a1c-4ddd-b248-5c20e42b84d7_v3](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/65726257-99b5-4a8d-8471-5e2d8663cd99)

where "docs" is Segoe UI Bold 24 pt

### Current result (.logo width is set to 200px):

![logo preview](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/5dbce278-5e37-47a2-b4b5-8196efa86406)


### Graphic defects:

- I cannot make the black border (the outline) of the word "docs" similar to that in the word "Sandboxie"
- The grey mark near to the S of Sandboxie (also present in your merged logo):
![S letter of Sandboxie logo](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/cdab91e9-1043-4ef7-84be-2eb734eb3d17)

2024-06-24 14:11 UTC, QZLin commented
Cleaned up the leftover pixels and add shadow to "docs" text
![sandmerge](https://github.com/sandboxie-plus/sandboxie-docs/assets/38138000/86c50aa8-05c0-4872-9335-b852d03b50d9)
Preview with background color:
![preview](https://github.com/sandboxie-plus/sandboxie-docs/assets/38138000/56a732ea-03f5-4c66-9737-d074b5f31d6a)

2024-07-30 19:54 UTC, isaak654 commented
Could you help me to fix the following points before merging?

- [ ] 1) Apply [this](https://private-user-images.githubusercontent.com/12372772/342458489-e854dcc6-361f-4d50-bdab-b16500425f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjg4MzAsIm5iZiI6MTcyMjM2ODUzMCwicGF0aCI6Ii8xMjM3Mjc3Mi8zNDI0NTg0ODktZTg1NGRjYzYtMzYxZi00ZDUwLWJkYWItYjE2NTAwNDI1ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5NDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDg3ZDU3ODJhNmRlNjZjNDZhMmYzMGJjN2ZmODQ2YTEzZWNjYjY5OWVkMmNkODgxNThkZjJjOTZmZjdiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lFhm5WDd8iPPTb2qM0UZQWjH73VDFS7KW72WDrkU_ro) logo
- [ ] 2) Apply the correct width for .logo CSS class
- [ ] 3) Fix the conflicting files

2024-07-30 19:55 UTC, isaak654 commented
I have merged the previous PRs and decided which logo to adopt.

Could you help me to fix the following points before merging?

- [ ] 1) Apply [this](https://private-user-images.githubusercontent.com/12372772/342458489-e854dcc6-361f-4d50-bdab-b16500425f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjg4MzAsIm5iZiI6MTcyMjM2ODUzMCwicGF0aCI6Ii8xMjM3Mjc3Mi8zNDI0NTg0ODktZTg1NGRjYzYtMzYxZi00ZDUwLWJkYWItYjE2NTAwNDI1ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5NDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDg3ZDU3ODJhNmRlNjZjNDZhMmYzMGJjN2ZmODQ2YTEzZWNjYjY5OWVkMmNkODgxNThkZjJjOTZmZjdiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lFhm5WDd8iPPTb2qM0UZQWjH73VDFS7KW72WDrkU_ro) logo
- [ ] 2) Apply the correct width for .logo CSS class
- [ ] 3) Fix the conflicting files

2024-07-31 07:13 UTC, QZLin commented
> I have merged the previous PRs and decided which logo to adopt.
> 
> Could you help me to fix the following points before merging?
> 
>     * [ ]  1) Apply [this](https://private-user-images.githubusercontent.com/12372772/342458489-e854dcc6-361f-4d50-bdab-b16500425f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjg4MzAsIm5iZiI6MTcyMjM2ODUzMCwicGF0aCI6Ii8xMjM3Mjc3Mi8zNDI0NTg0ODktZTg1NGRjYzYtMzYxZi00ZDUwLWJkYWItYjE2NTAwNDI1ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5NDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDg3ZDU3ODJhNmRlNjZjNDZhMmYzMGJjN2ZmODQ2YTEzZWNjYjY5OWVkMmNkODgxNThkZjJjOTZmZjdiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lFhm5WDd8iPPTb2qM0UZQWjH73VDFS7KW72WDrkU_ro) logo
> 
>     * [ ]  2) Apply the correct width for .logo CSS class
> 
>     * [ ]  3) Fix the conflicting files

The logo link seems broken (Got 404 not found)

2024-07-31 08:28 UTC, isaak654 commented
> The logo link seems broken (Got 404 not found)

Not anymore, I've just updated the link.

2024-07-31 08:34 UTC, QZLin commented
https://github.com/QZLin/sandboxie-docs/commit/85fd13c67336b62588401c4dbad68ca5d4ed92b1
I'm not sure if splitting the readme into repo readme and docs readme is a good idea.
But the links of readme.md and docs/readme.md have to be different because of the mkdocs project structure.Then we will have to always do the sync jobs for two similar files.
```
// readme.md
[Getting Started with Sandboxie](docs/Content/GettingStarted.md)

// docs/readme.md
[Getting Started with Sandboxie](Content/GettingStarted.md)
```

2024-07-31 09:14 UTC, isaak654 commented
> I'm not sure if splitting the readme into repo readme and docs readme is a good idea.

I think renaming docs/readme.md to docs/index.md could help to prevent confusion, while in the root README:

```
# Sandboxie documentation

README is located at [docs/index.md](docs/index.md)
```

2024-08-01 21:51 UTC, isaak654 commented
The search box under the logo suddenly disappeared.

2024-08-02 03:18 UTC, QZLin commented
> The search box under the logo suddenly disappeared.

Fixed

2024-08-04 15:09 UTC, isaak654 approved these changes

2024-08-04 20:09 UTC, merged