Trace log updating to current options and more details
sandboxie-plus/sandboxie-docs pull request #56
Opened 2022-03-17 09:34 UTC by mitchcapper

2022-03-17 12:27 UTC, isaak654 requested changes
I think SBPlusTraceLog.png needs to be enlarged to comprehend the Status dropdown and the two buttons to the right of the "Trace Log" tab.

2022-03-17 13:02 UTC, isaak654 requested changes

2022-03-17 13:02 UTC, isaak654 commented on Content/TraceLog.md
> +
It may worth mentioning that you can also save the log as file (the icon is represented by a floppy disk).

2022-03-17 13:02 UTC, isaak654 commented on Content/SandboxieTrace.md
> +If you configure these options using the [Sandboxie Agent](SandboxieAgent.md) they will be configured to log all requests (both successful and failed request).  If you want to only log one result you
Even if David tends to use the Sandboxie Agent definition, I think Sandboxie UI would be more appropriate to a wider audience.

2022-03-17 13:22 UTC, isaak654 requested changes

2022-03-17 13:22 UTC, isaak654 commented on Content/TraceLog.md
> +**Important:** Please use the Trace Log tool only if you are asked to do so.
>  **Important:** Please use the Trace Log tool only if you are asked to do so. 

This short warning is also in the Classic page of Resource Access Monitor, I think it may worth considering to erase it or edit it just to specify you need to use it to locate specific issues.

2022-03-17 18:05 UTC, mitchcapper commented
> I think SBPlusTraceLog.png needs to be enlarged to comprehend the Status dropdown and the two buttons to the right of the "Trace Log" tab.

Agreed when I was doing final review in comparison to the Control pages I noticed that.  Do we want to crop the photo to more easily make it bigger?   

That was also my mistake by making the SB Plus window a bit more compact make the screenshots easier to see.  I have a slight issue that SB Plus (or potentially more a QT issue) isn't 100% DPI friendly so some things look odd).  Here is an example of sandboxie next to VS for comparison.    I  would probably redo the screenshots using another PC to fix (or a VM).   I think without the larger than normal controls it may fit even in a  window of that size. I know @hippalectryon-0 has a good number of screenshots so not sure if best to have one primary set anyway (his are on dark theme I believe).  
![image](https://user-images.githubusercontent.com/1643324/158867323-ffefd005-b8c5-4697-9b3d-448b73776327.png)

2022-03-17 18:06 UTC, mitchcapper commented on Content/TraceLog.md
> +
Will add

2022-03-17 18:07 UTC, mitchcapper commented on Content/TraceLog.md
> +**Important:** Please use the Trace Log tool only if you are asked to do so.
Agree on this, I almost removed that line already.  I figured it might be best to not make policy changes though without calling it out.  Will update it on both pages as I think many sandboxie users may already be decently technical and find it useful.

2022-04-21 16:21 UTC, isaak654 commented
The Trace log UI has changed since [Plus 1.0.16](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.16) with a new monitor mode (that is a new button to toggle), so the screenshot should be redone anyway.

* Added "Monitor Mode" to the resource access trace, similar to the old monitor view of SbieCtrl.exe

2023-10-17 20:39 UTC, closed without merging