Typo Fix(PlusMigrationGuide.md)
sandboxie-plus/sandboxie-docs pull request #69
Opened 2022-09-19 12:23 UTC by Luro223

2022-09-19 13:46 UTC, Luro223 commented
Need additional info related to "snapshot management" @isaak654

2022-09-19 16:51 UTC, isaak654 requested changes

2022-09-19 16:51 UTC, isaak654 commented on Content/PlusMigrationGuide.md
> +To copy a existing box configuration the "Duplicate Sandbox" menu command can be used.
```suggestion
To copy a existing box configuration, the "Duplicate Sandbox" menu command can be used.
```

2022-09-19 16:55 UTC, isaak654 commented
> Need additional info related to "snapshot management" @isaak654

I doubt it, this is a generic comparison between the features of Sandboxie Classic (which has no snapshot management) and Plus ones.

2022-09-19 21:21 UTC, isaak654 requested changes

2022-09-19 21:21 UTC, isaak654 commented on Content/PlusMigrationGuide.md
> +On this tab, the shell integration can be configured. Most functions are available, although deprecated features were dropped and other options were moved out.
```suggestion
On this tab, the shell integration can be configured. Most functions are available, although some deprecated features were dropped and other options were moved out.
```

2022-09-19 21:21 UTC, isaak654 commented on Content/PlusMigrationGuide.md
> +Additionally, using the WFP facility, a full per sandbox firewall can be configured (tab "Internet Restrictions" --> sub tab "Network Firewall Rules").
```suggestion
Additionally, using the WFP facility, a per sandbox firewall can be configured (tab "Internet Restrictions" --> sub tab "Network Firewall Rules").
```

2022-09-26 19:35 UTC, isaak654 requested changes

2022-09-26 19:35 UTC, isaak654 commented on Content/PlusMigrationGuide.md
> +The over all layout of the main window of sandman.exe is exactly the same as the old one of sbiectrl.exe when the "Simple View" is chosen. If the "Advanced View" is chosen, there are three additional
```suggestion
The overall layout of the main window of SandMan.exe is exactly the same as the old one in Sbiectrl.exe when the "Simple View" is chosen. If the "Advanced View" is chosen, there are three additional tabs on the bottom of the window ("Sbie Messages" etc.), so it corresponds with what can be seen in the right picture.
```

2022-09-26 19:35 UTC, isaak654 commented on Content/PlusMigrationGuide.md
> +The window "Files" offers the same functionality as the old view, but enhances it by providing a full windows context menu.
```suggestion
The window "Files" offers the same functionality as the old view, but enhances it by providing a full context menu.
```

2022-09-27 12:48 UTC, isaak654 approved these changes

2022-09-27 12:49 UTC, merged