Typo Fix(SandboxHierarchy.md)
sandboxie-plus/sandboxie-docs pull request #78
Opened 2022-09-19 12:33 UTC by Luro223

2022-09-19 21:46 UTC, isaak654 requested changes

2022-09-19 21:46 UTC, isaak654 commented on Content/SandboxHierarchy.md
> +When sandboxed programs create (or modify) objects, such as files, in fact, some kind of project should be created. Sandboxie creates these objects out of the way, to protect the system from harmful
```suggestion
When sandboxed programs create (or modify) objects, such as files, in fact, some kind of data should be created. Sandboxie creates these objects out of the way, to protect the system from harmful changes. But these objects must reside somewhere in the system. This page describes where various types of sandboxed objects are placed.
```

2022-09-19 21:46 UTC, isaak654 commented on Content/SandboxHierarchy.md
> +Files are created in the sandbox folder in the following hierarchy:
```suggestion
Files are created in the Sandbox folder according to the following hierarchy:
```

2022-09-19 21:46 UTC, isaak654 commented on Content/SandboxHierarchy.md
> +Files are created in the sandbox folder in the following hierarchy:
2) I would also suggest to replace the remaining `sandbox folder` references in the page with `Sandbox folder`

2022-09-21 12:28 UTC, Luro223 commented
@isaak654 github shows "isaak654requested changes 2 days ago" even though I accepted all changed :/

2022-09-21 12:40 UTC, isaak654 commented
It's because GitHub tends to present everything for history purposes. 
With regard to the pull requests that are still open, I'm taking some time for other things.

2022-09-21 13:36 UTC, Luro223 commented
Okay, got it.

2022-09-26 20:30 UTC, isaak654 approved these changes

2022-09-27 12:35 UTC, merged